# Set the base theme
theme: "jekyll-theme-cayman"

# Misc.
encoding: "utf-8"
site.lang: "en-US"

# Setup SEO
title: "Clover Build Repository"
description: "Automated Clover Builds"
url: "https://cloverdb.com"
author: "Dids"
twitter:
  username: "Dids"
  card: "summary"
logo: "/assets/logo.png"
social:
  name: "Dids"
  links:
    - https://twitter.com/Dids
    - https://github.com/Dids
lang: "en_US"

# Hide default download buttons
show_downloads: false

# Default number of releases to show
release_count: 10

# Setup Google Analytics
google_analytics: "UA-2387272-36"

# Setup GitHub specific configurations
github:
  is_project_page: false # Used with CSS to hide "View on GitHub" button

# The release of Jekyll Now that you're using
#version: v1.2.0
version: v3.8.5

markdown: kramdown
# markdown: CommonMarkGhPages

# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  #syntax_highlighter_opts:
  #  # Use existing pygments syntax highlighting css
  #  css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
